export const terribleTraitsTable = ["Lush",
"stubborn",
"Mocking sardonic cheer",
"loud",
"stupid",
"coward",
"cocky",
"Slightly insane",
"aggressive",
"anxious",
"cheater",
"selfish",
"lazy",
"hedonistic",
"impulsive",
"ostentatious",
"paranoid",
"pretentious",
"sadistic",
"disloyal"]

export const brokenBodyTable = ["Missing an Eye",
"Missing an ear",
"Matted, dreaded hair",
"missing a leg. Peg leg or crutch.",
"Missing a hand. Hook or claw instead [d6].",
"Deep bilge stench.",
"Many, many sailor tattoos.",
"(Almost) never blinks.",
"Most teeth have rotted out or have been broken.",
"Twitches constantly, especially trigger finger",
"A nigh incurable case of scurvy. Permanently bleeding gums.",
"Syphilis",
"Gout",
"Gaunt",
"fat",
"bad gas",
"Infested with bugs",
"tongue has been cut out",
"Hideously ugly",
"So good looking people are jealous"]

export const badHabitTable = ["Smokes constantly. ",
"Functioning Alcoholic",
"Bets on everything possible.",
"O.C.D. Constantly counting.",
"Eating rats is your favorite past time.",
"Afraid of prime numbers larger than 3. d20 rolls of 5, 7, 11, 13, and 17 fill you with superstitious terror.",
"Become a murderous grump when hungry.",
"Habitual Procrastinator.",
"Voluntary Insomniac",
"Prefer to shoot first, and never ask questions.",
"Overly, annoyingly religious.",
"You know every tall tale ever told. You make sure everyone else knows you know them.",
"You collect something. You talk to your collection. They are your friends.",
"Always trying to trick your crew mates, just for fun.",
"Why pay for anything when you can steal it?",
"Talk to yourself when alone, but you often think you are alone when you aren't.",
"You secretly enjoy the taste of human flesh.",
"You always \"know the right way\", but are prone to getting lost.",
"Blame others for every mistake.",
"Extremely obsessive with tasks and relationships."]

export const troublingTaleTable = ["Loved ones were burned alive. Revenge is imminent. ",
"Known pirate. Facing the gallows if caught.",
"Betrayed former crew mates. Now they hunt you.",
"Were marooned on an island for far too long. The voices MUST be real.",
"You stole a ship. The owner wants your money or your head, but will settle for both.",
"You escaped captivity, and will *never* go back.",
"A close relative has become your greatest enemy.",
"The last three ships you crewed all sank.",
"Your last crew was killed by undead. They let you live on purpose.",
"Political leaders hold loved one(s) as prisoners.",
"A Vodou Lwa spirit you don't like possesses you regularly.",
"You wronged a infamous pirate lord.",
"Narrowly escaped a cannibalistic ending.",
"You slaughtered them. Like ANIMALS.",
"Mysterious lone survivor of a lucrative treasure expedition.",
"[d2] 1:Failed Mutineer. 2:Successful mutineer.",
"A silent ghost haunts you. It is always there, but only you can see it.",
"Deserted your country's military; maybe they think you are dead?",
"You have no memory before a few days ago.",
"You died once already, but Hell didn't want you."]

export const placeOfImportanceTable = ["The Yucatan ",
"Havana, Cuba",
"Mosquito Coast",
"Nassau, Bahamas",
"Port Royal, Jamaica",
"Tortuga",
"Port-au-Prince",
"Maracaibo",
"Santo Domingo",
"San Jaun",
"Guadeloupe",
"Barbados"]

export const thingOfImportanceTable = ["an animal pelt ",
"an oyster pearl",
"a silver locket",
"a conch shell",
"a pipe carved from wood",
"a pipe carved from bone",
"a small jade figurine",
"a shard of crystal",
"a Mesoan gold coin",
"a ruined piece of a treasure map",
"a treasure map of an unknown place",
"a diary written by an ancestor",
"a silver ring",
"an ivory chess piece",
"a sea creature carved from obsidian",
"a spherical gem that functions like a prism",
"a jar containing a severed hand, eyeball, or organ",
"a necklace made of bones and feathers",
"a book of scripture",
"a novel you loved as a child",
"a silk handkerchief from a distant land",
"a pouch containing different animal teeth",
"an old fillet knife",
"a fossil of an extinct fish",
"a piece of colorful coral",
"a small ship in a bottle",
"a letter from a loved one",
"the journal of a dead explorer",
"a stone embossed with a beautiful mermaid",
"a vial of holy water, from clergy in your hometown",
"a jar with the remains of a small squid",
"precious salts and spices, in a tiny chest",
"a tankard made from a horn",
"a jar of the finest tobacco",
"a golden letter opener",
"a cast bronze owl, the size of  a deck of cards",
"a collection of sea shells and rocks",
"a necklace carved from jade",
"a recently deceased relative's will, naming you as the sole heir",
"a drawing of a loved one",
"a bag of white powder you believe may be magical",
"an old rusted key with a blue gem that glows in the moonlight",
"a compass that doesn't point north",
"a clay jar you are using as an urn",
"definitive proof of an enemy's (or loved one's) crime",
"a small golden bell",
"a old bottle of red wine (Bordeaux, incredible vintage)",
"a jar of dried jellyfish dust",
"a multi-colored feather from an exotic bird",
"a necklace from a loved one",
"a gold ring that is too small to fit on your fingers",
"a single diamond earring",
"a finely made leather eye patch",
"a set of gardening tools",
"a dried flower",
"an animal skull",
"a human skull",
"a gem that glows when submerged in seawater",
"a dinosaur bone or claw",
"a jar of fireflies",
"a leather bound tome in a language you don't recognize",
"the blueprints to a new type of ship",
"a carved arrowhead",
"a stone tablet inscribed with ancient pictographs or hieroglyphs",
"a perfect cube made of crystal",
"significant tattoo, d4:1 love, 2 revenge, 3 ancestors, 4 unknown origin",
"a bottle of perfumed oil",
"a broken set of manacles",
"a pistol with one shot meant for someone special",
"a flag of personal significance",
"a broken compass with a mysterious significance",
"a broken spyglass with a scroll or map hidden inside",
"a length of rope you made",
"carved gaming pieces",
"a set of rune stones",
"a twig from a very old tree",
"the end of a rope noose taken from a corpse, a very bad memory",
"a 6' length of chain",
"4d20 scars from lashes on your back",
"a long scar on your face",
"1d4 missing finger and/or toes",
"a missing eye (roll d2)",
"a missing limb (roll d4)",
"a set of keys on a large key ring",
"a small keg of something valuable (rum, powder, ashes)",
"a magnifying lens (glass only)",
"the cork from a bottle, from a special occasion",
"a cannonball",
"a deck of cards with 1d4 cards missing and 1d6 \"extra\" cards",
"a garment from someone special",
"a wanted poster, d4:1 legend, 2 loved one, 3 enemy, 4 stranger",
"a fancy wig",
"a letter of political importance",
"tanned whale skin or a jar of blubber",
"a petrified egg",
"a monkey paw with 1 finger extended",
"a memorized poem that sounds like a treasure map",
"a golden necklace that could be the top of a staff",
"a talisman shaped like a snake",
"a glass vial of dark blood"]

export const backgroundTable = ["sailor: 2d6 x 10s & a reason to go to sea ",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"sailor: 2d6 x 10s & a reason to go to sea",
"actor: 2d6 x 10s & a play or book",
"apothecary: 2d6 x 10s & healing kit",
"artist: 2d6 x 10s & art supplies",
"assassin: 2d6 x 10s & a dagger",
"bandit: 2d6 x 10s & a club",
"barkeep: 2d6 x 10s & a flask of fine rum",
"blacksmith: 2d6 x 10s & a set of files and tools",
"bosun: 2d6 x 10s & the respect of some crew",
"business man: 3d6 x 10s & a profitable past",
"cabin boy: 2d4 x 10s & a small toy or trinket",
"captain: 2d8 x 10s & a spyglass",
"former captive: 2d4 x 10s & your freedom",
"castaway: 2d4 x 10s & a keepsake from the island",
"chef: 2d6 x 10s & a book of recipes",
"cook: 2d6 x 10s & some fine cooking spices",
"craftsman: 2d6 x 10s & a set of tools",
"criminal: 1d10 x 10s & lockpick or a crowbar",
"cultist: 2d6 x 10s & a book of scripture",
"deserter: 2d4 x 10s & a small bounty on your head",
"doctor: 2d6 x 10s & a medical kit",
"explorer: 2d6 x 10s & a map and compass",
"farmer: 2d4 x 10s & a reason to leave your farm",
"first mate: 2d6 x 10s & a loyal friend",
"gambler: 1d12 x 10s & a sizable debt",
"grave robber: 2d6 x 10s & something from a corpse",
"guard: 2d6 x 10s & a keen eye for mischief",
"gunner: 2d6 x 10s & skill at shooting",
"harlot: 2d8 x 10s & an admirer and syphilis",
"heretic: 2d4 x 10s & a blasphemous disposition",
"homemaker: 2d6 x 10s & a loved one back home",
"hunter: 2d6 x 10s & a hunting knife",
"indentured servant: 2d4 x 10s & someone looking for you",
"innkeeper: 3d4 x 10s & a small inn somewhere",
"landowner: 3d6 x 10s & property somewhere",
"loner: 2d6 x 10s & a dislike of others",
"cartographer: 2d6 x 10s & map making tools",
"marine: 2d6 x 10s & a military cutlass",
"medic: 2d6 x 10s & a medical kit",
"merchant: 2d8 x 10s & good negotiating skills",
"military: 2d6 x 10s & combat training",
"missionary: 2d4 x 10s & a holy symbol and scripture",
"monk: 2d6 x 10s & a holy symbol and scripture",
"musician: 2d6 x 10s & [roll on instrument table on page 7]",
"native: 2d4 x 10s & something from your homeland",
"navigator: 2d6 x 10s & a compass",
"noble: 3d6 x 10s & good manners",
"nurse: 2d6 x 10s & a medical kit",
"officer: 2d8 x 10s & a cutlass and military training",
"orphan: 2d4 x 10s & a longing for new parental figures",
"performer: 2d6 x 10s & [roll on instrument table on page 7]",
"philosopher: 2d6 x 10s & a book and a puzzling disposition",
"pilot: 2d6 x 10s & a compass",
"pirate: 2d6 x 10s & an empty bottle of rum",
"politician: 2d6 x 10s & skill a deception",
"priest: 2d6 x 10s & a holy symbol and scripture",
"privateer: 2d6 x 10s & a letter of marque [roll Faction d4 pg.4]",
"quartermaster: 2d6 x 10s & the respect of a ship's crew",
"refugee: 2d4 x 10s & strong survival instincts",
"religious follower: 2d4 x 10s & a strong sense of faith",
"revolutionary: 2d6 x 10s & bold plans and a few allies",
"rumored sorcerer: 2d6 x 10s & dark and powerful knowledge",
"runaway: 2d4 x 10s & a desire for a new home",
"sail maker: 2d6 x 10s & skill with sails",
"scholar: 2d6 x 10s & a few books",
"scoundrel: 2d8 x 10s & a few enemies along the way",
"scout: 2d6 x 10s & keen senses and a map",
"shaman: 2d4 x 10s & herbs and mystic knowledge",
"shipwright: 2d6 x 10s & skill with woodworking",
"slave: 2d4 x 10s & a seething desire for revenge",
"smuggler: 2d6 x 10s & a bounty on your head",
"soldier: 2d6 x 10s & a tactical mind",
"spy: 2d6 x 10s & a dark cloak",
"student: 2d4 x 10s & a strong will to learn",
"surgeon: 2d6 x 10s & a medical kit",
"thief: 1d12 x 10s & lock picks",
"vagabond: 2d4 x 10s & a leather backpack",
"victim: 2d6 x 10s & a haunted past",
"tribal warrior: 2d4 x 10s & a cultural weapon",
"whaler: 2d6 x 10s & a harpoon",
"writer: 2d6 x 10s & ink, quills, and parchment"]